In [1]:
import numpy as np # linear algebra
import pandas as pd

In [2]:
credits= pd.read_csv('tmdb_5000_credits.csv')
movies=pd.read_csv('tmdb_5000_movies.csv')

In [3]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [4]:
movies.shape

(4803, 20)

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies = movies.merge(credits,on='title')

In [7]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [8]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
import ast

In [10]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [11]:
movies.dropna(inplace=True)

In [12]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [13]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [14]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [15]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [16]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [17]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [18]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [20]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [21]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [22]:
movies['overview']=movies['overview'].apply(lambda x:x.split())#it will convert

In [23]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [24]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])

In [25]:
movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])

0       [cultureclash, future, spacewar, spacecolony, ...
1       [ocean, drugabuse, exoticisland, eastindiatrad...
2       [spy, basedonnovel, secretagent, sequel, mi6, ...
3       [dccomics, crimefighter, terrorist, secretiden...
4       [basedonnovel, mars, medallion, spacetravel, p...
                              ...
4804    [unitedstates–mexicobarrier, legs, arms, paper...
4805                                                   []
4806    [date, loveatfirstsight, narration, investigat...
4807                                                   []
4808             [obsession, camcorder, crush, dreamgirl]
Name: keywords, Length: 4806, dtype: object

In [26]:
movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])

0       [SamWorthington, ZoeSaldana, SigourneyWeaver, ...
1       [JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...
2       [DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...
3       [ChristianBale, MichaelCaine, GaryOldman, Anne...
4       [TaylorKitsch, LynnCollins, SamanthaMorton, Wi...
                              ...
4804    [CarlosGallardo, JaimedeHoyos, PeterMarquardt,...
4805    [EdwardBurns, KerryBishé, MarshaDietlein, Cait...
4806    [EricMabius, KristinBooth, CrystalLowe, GeoffG...
4807    [DanielHenney, ElizaCoupe, BillPaxton, AlanRuc...
4808    [DrewBarrymore, BrianHerzlinger, CoreyFeldman,...
Name: cast, Length: 4806, dtype: object

In [27]:
movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])#this method will remove spaces between nanme

0                              [JamesCameron]
1                             [GoreVerbinski]
2                                 [SamMendes]
3                          [ChristopherNolan]
4                             [AndrewStanton]
                        ...
4804                        [RobertRodriguez]
4805                            [EdwardBurns]
4806                             [ScottSmith]
4807                             [DanielHsia]
4808    [BrianHerzlinger, JonGunn, BrettWinn]
Name: crew, Length: 4806, dtype: object

In [28]:
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [30]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [31]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [32]:
new_df=movies[['movie_id','title','tags']]#new dataset after removing unwanted columns

In [33]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [34]:
new_df['tags'].apply(lambda x:" ".join(x))#it will convert list into string

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [35]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\ronak\AppData\Local\Temp\ipykernel_14512\487797088.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [36]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [37]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez GiovanniRibisi JoelDavidMoore CCHPounder WesStudi LazAlonso DileepRao MattGerald SeanAnthonyMoran JasonWhyte ScottLawrence KellyKilgour JamesPatrickPitt SeanPatrickMurphy PeterDillon KevinDorman KelsonHenderson DavidVanHorn JacobTomuri MichaelBlain-Rozgay JonCurry LukeHawker WoodySchultz PeterMensah SoniaYee JahnelCurfman IlramChoi KylaWarren LisaRoumain DebraWilson ChrisMala TaylorKibby JodieLandau JulieLamm CullenB.Madden JosephBradyMadden FrankieTorres AustinWilson SaraWilson TamicaWashington-Miller LucyBriant NathanMeister GerryBlair MatthewChamberlain PaulYates WrayWilson JamesGaylyn MelvinLenoClarkIII CarvonFutrell BrandonJelkes MicahMoch HanniyahMuhammad ChristopherNolen ChristaOliver AprilMarieThomas BravitaA.Threatt ColinBleasdale MikeBodnar MattClayton NicoleDionne JamieHarrison AllanHenry AnthonyIngruber AshleyJeffery DeanKnowsley JosephMika-Hunt TerryNotary KaiPantano LoganPithyou StuartPollock Raja GarethRuck RhianSheehan T.J.Storm JodieTaylor AliciaVela-Bailey RichardWhiteside NikieZambo JuleneRenee JamesCameron'

In [38]:
new_df['tags'].apply(lambda x:x.lower())#it will convert into a lower case

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bond’s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [39]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

C:\Users\ronak\AppData\Local\Temp\ipykernel_14512\4224080999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [40]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [41]:
#text vectorization
new_df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez giovanniribisi joeldavidmoore cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyte scottlawrence kellykilgour jamespatrickpitt seanpatrickmurphy peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurry lukehawker woodyschultz petermensah soniayee jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibby jodielandau julielamm cullenb.madden josephbradymadden frankietorres austinwilson sarawilson tamicawashington-miller lucybriant nathanmeister gerryblair matthewchamberlain paulyates wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrell brandonjelkes micahmoch hanniyahmuhammad christophernolen christaoliver aprilmariethomas bravitaa.threatt colinbleasdale mikebodnar mattclayton nicoledionne jamieharrison allanhenry anthonyingruber ashleyjeffery deanknowsley josephmika-hunt terrynotary kaipantano loganpithyou stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhiteside nikiezambo julenerenee jamescameron'

In [42]:
#stamming
#word like love loving loves so after applying stamming we willget ans as love lov love
#!pip install nltk
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [43]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [44]:
new_df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [45]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\ronak\AppData\Local\Temp\ipykernel_14512\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [46]:
new_df['tags'][1]

"captain barbossa, long believ to be dead, ha come back to life and is head to the edg of the earth with will turner and elizabeth swann. but noth is quit as it seems. adventur fantasi action ocean drugabus exoticisland eastindiatradingcompani loveofone'slif traitor shipwreck strongwoman ship allianc calypso afterlif fighter pirat swashbuckl aftercreditssting johnnydepp orlandobloom keiraknightley stellanskarsgård chowyun-fat billnighi geoffreyrush jackdavenport kevinmcn tomholland naomieharri jonathanpryc keithrichard leearenberg mackenziecrook gregelli davidbaili martinklebba davidschofield laurenmah vanessabranch angusbarnett gilesnew reggiele dominicscottkay takayofisch davidmeuni ho-kwants andybeckwith peterdonaldbadalamentiii christophers.capp keithrichard hakeemkae-kazim ghassanmassoud goreverbinski"

In [47]:
#so we will do text vectorization we will use bag of word technique there are so many technique that we are usingexample are wordtovac exc
#ba gofword

In [48]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [49]:
cv.fit_transform(new_df['tags']).toarray().shape

(4806, 5000)

In [50]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [51]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [52]:
len(cv.get_feature_names())

C:\Users\ronak\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

5000

In [53]:
cv.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930',
 '1940',
 '1950',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1980',
 '1990',
 '19th',
 '19thcenturi',
 '20',
 '20th',
 '24',
 '25',
 '30',
 '3d',
 '40',
 '50',
 '60',
 '70',
 'aaron',
 'aaroneckhart',
 'aarontaylor',
 'aasifmandvi',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'abov',
 'abus',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'act',
 'action',
 'activ',
 'activist',
 'actor',
 'actress',
 'actual',
 'adam',
 'adambrodi',
 'adamgoldberg',
 'adamlefevr',
 'adamsandl',
 'adamscott',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adewaleakinnuoye',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrianmartinez',
 'adrianscarborough',
 'adrienbrodi',
 'adult',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'agbaj',
 'age',
 'agediffer',
 'agency',
 'agenda',
 'agent',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airport',
 'aka',
 'al',
 'alabama',
 'alanalda',
 'alanarkin',
 'alancum',
 'alanrickman',
 'alantudyk',
 'alaska',
 'albert',
 'albertbrook',
 'albertfinney',
 'alcohol',
 'alecbaldwin',
 'alecguin',
 'alessandronivola',
 'alex',
 'alexandersiddig',
 'alexanderskarsgård',
 'alexapenavega',
 'alexborstein',
 'alexisbledel',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'alfrewoodard',
 'ali',
 'alic',
 'alice',
 'alicedrummond',
 'aliciawitt',
 'alien',
 'alieninvas',
 'alienlife',
 'alilart',
 'aliv',
 'alive',
 'allancordun',
 'allen',
 'allencovert',
 'alleong',
 'alli',
 'allianc',
 'allisonjanney',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'ambassador',
 'amberheard',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanfootbal',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amus',
 'amyadam',
 'amypoehl',
 'amyryan',
 'amysedari',
 'amysmart',
 'anagastey',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andreamartin',
 'andrebraugh',
 'andrew',
 'andrewdali',
 'android',
 'andydick',
 'andygarcía',
 'andyricht',
 'andysamberg',
 'andyserki',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'angelo',
 'anger',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'annalevin',
 'annapaquin',
 'annasophiarobb',
 'anndowd',
 'anne',
 'annebancroft',
 'annefletch',
 'annehathaway',
 'annehech',
 'annemoss',
 'annetteben',
 'anni',
 'annikaperga',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antihero',
 'antonicoron',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypt',
 'appar',
 'appear',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'arab',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'arena',
 'arielwint',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'arminmueller',
 'armor',
 'armsdeal',
 'armstrong',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'arthurj',
 'arthurtovey',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'ask',
 'aspir',
 'assassin',
 'assault',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'athlet',
 'atomicbomb',
 'attack',
 'attempt',
 'attend',
 'attent',
 'attitud',
 'attorney',
 'attract',
 'audienc',
 'audit',
 'august',
 'aunjanueelli',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'auto',
 'avaacr',
 'aveng',
 'avoid',
 'await',
 'awaken',
 'award',
 'away',
 'awri',
 'awry',
 'azizansari',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'bad',
 'bag',
 'bahama',
 'bail',
 'bailey',
 'balanc',
 'ball',
 'ballet',
 'band',
 'banish',
 'bank',
 'banker',
 'bankrobberi',
 'baptist',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrypepp',
 'barryshabakahenley',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'bear',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'becam',
 'becaus',
 'beccasweitz',
 'becom',
 'becominganadult',
 'bed',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'behavior',
 'belief',
 'believ',
 'bell',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'benchaplin',
 'bend',
 'benedictcumberbatch',
 'benfost',
 'bengazzara',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'benmendelsohn',
 'bennett',
 'benstil',
 'bent',
 'benwhishaw',
 'berlin',
 'bernardhil',
 'bernardle',
 'berniemac',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'bethgrant',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'big',
 'biggest',
 'biker',
 'billcamp',
 'billcobb',
 'billduk',
 'billhad',
 'billi',
 'billionair',
 'billmoseley',
 'billmurray',
 'billnighi',
 'billnunn',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billyburk',
 'billyconnolli',
 'billycrudup',
 'billycryst',
 'billydeewilliam',
 'billyslaught',
 'billywest',
 'billyzan',
 'biographi',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blade',
 'blakeclark',
 'blame',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'blythedann',
 'board',
 'boat',
 'bob',
 'bobbalaban',
 'bobbergen',
 'bobbi',
 'bobbycannaval',
 'bobbyfarrelli',
 'bobgunton',
 'bobhoskin',
 'bobstephenson',
 'bodi',
 'body',
 'bodyguard',
 'bokeemwoodbin',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'bonniehunt',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'bound',
 'bounti',
 'bountyhunt',
 'box',
 'boxer',
 'boy',
 'boydbank',
 'boydholbrook',
 'boyfriend',
 'boys',
 'braddourif',
 'bradgarrett',
 'bradleycoop',
 'bradleywhitford',
 'bradpitt',
 'bradwilliamhenk',
 'brain',
 'brand',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breckinmey',
 'brendanfras',
 'brendangleeson',
 'brendansextoniii',
 'brentbrisco',
 'brentspin',
 'brettcullen',
 'brettratn',
 'brian',
 'briancox',
 'briandennehi',
 'briandepalma',
 'briandoyle',
 'brianj',
 'briano',
 'bride',
 'bridg',
 'bridgettewilson',
 'brief',
 'brielarson',
 'brien',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadway',
 'broke',
 'broken',
 'brook',
 'brooklyn',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucecampbel',
 'brucedern',
 'brucegreenwood',
 'brucemcgil',
 'brucesp',
 'brucewilli',
 'brutal',
 'bryan',
 'bryancranston',
 'bryansing',
 'brycedallashoward',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddycomedi',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'buri',
 'burn',
 'burtreynold',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butler',
 'buy',
 'byrn',
 'cabin',
 'cal',
 'california',
 'callumkeithrenni',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameron',
 'cameronbright',
 'camerondiaz',
 'camgigandet',
 'camp',
 'campaign',
 'campbel',
 'campbellscott',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candid',
 'cannib',
 'capabl',
 'capit',
 'captain',
 'captiv',
 'captur',
 'car',
 'caraccid',
 'caraseymour',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagallo',
 'carlagugino',
 'carlo',
 'carlosalazraqui',
 'carmen',
 'carmenelectra',
 'carol',
 'carolineaaron',
 'carolinegoodal',
 'carolkan',
 'carrac',
 'carri',
 'carrie',
 'carriefish',
 'cartel',
 'carter',
 'cary',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinekeen',
 'catherineo',
 'catherinezeta',
 'cathey',
 'cathol',
 'catholic',
 'caught',
 'caus',
 'cave',
 'cedrictheentertain',
 'celebr',
 'celiaimri',
 'celiaweston',
 'cellphon',
 'cemeteri',
 'center',
 'central',
 'centuri',
 'centuries',
 'century',
 'certain',
 'chadmichaelmurray',
 'chain',
 'chainsaw',
 'challeng',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chancekelli',
 'chang',
 'channingtatum',
 'chao',
 'chaos',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charlesd',
 'charlesdurn',
 'charlesnapi',
 'charless',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotterampl',
 'charltonheston',
 'charm',
 'chase',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheechmarin',
 'cheerlead',
 'chef',
 'chelcieross',
 'chemic',
 'cher',
 'cherryjon',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhood',
 'children',
 'chill',
 'chimcbrid',
 'china',
 'chines',
 'chip',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chrisbauer',
 'chrisbrown',
 'chriscolumbu',
 'chriscoop',
 'chriselli',
 'chrisevan',
 'chrishemsworth',
 'chriskattan',
 'chrisklein',
 'chrismessina',
 'chrismil',
 'chrismulkey',
 'chriso',
 'chrisowen',
 'chrisparnel',
 'chrispenn',
 'chrispin',
 'chrispratt',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christinaappleg',
 'christinaricci',
 'christinebaranski',
 'christma',
 'christmas',
 'christmasparti',
 'christoph',
 'christopherfairbank',
 'christopherguest',
 'christopherknight',
 'christopherlambert',
 'christopherle',
 'christopherlloyd',
 'christophermcdonald',
 'christophermeloni',
 'christophermintz',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chronicl',
 'church',
 'cia',
 'ciaránhind',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clancybrown',
 'clark',
 'clarkgregg',
 'clash',
 'class',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'cleaduval',
 'clean',
 'clear',
 'clerk',
 'client',
 'cliffcurti',
 'cliftoncollinsjr',
 'climat',
 'climb',
 'clinteastwood',
 'clinthoward',
 'cliveowen',
 'clock',
 'clone',
 'clorisleachman',
 'close',
 'closer',
 'clown',
 'club',
 'clue',
 'coach',
 'coast',
 'cocain',
 'code',
 'codycameron',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colehaus',
 'colinfarrel',
 'colinfirth',
 'colinhank',
 'colinsalmon',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleencamp',
 'colleg',
 'college',
 'collid',
 'collin',
 'collis',
 'colmfeor',
 'colmmeaney',
 'colonel',
 'coloni',
 'color',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comedi',
 'comedian',
 'comedy',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commit',
 'common',
 'commun',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compton',
 'comput',
 'concern',
 'concert',
 'condit',
 'confess',
 'confid',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connel',
 'connienielsen',
 'connieray',
 'connor',
 'conquer',
 'conradvernon',
 'consequ',
 'consequences',
 'consid',
 'conspir',
 'conspiraci',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'contest',
 'continu',
 'contract',
 'control',
 'controversi',
 'convent',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'core',
 'coreyburton',
 'coreystol',
 'corner',
 'corpor',
 'corps',
 'corrupt',
 'cost',
 'costum',
 'couldn',
 'count',
 'countri',
 'country',
 'countrysid',
 'coup',
 'coupl',
 'couple',
 'courag',
 'cours',
 'court',
 ...]

In [54]:
from sklearn.metrics.pairwise import cosine_similarity

In [55]:
cosine_similarity(vectors).shape

(4806, 4806)

In [56]:
similarity=cosine_similarity(vectors)

In [57]:
sorted(similarity[0],reverse=True)#similarity of 0 index

[1.0,
 0.2672612419124244,
 0.22961557339788816,
 0.22718473369882594,
 0.22247460415730486,
 0.22188007849009173,
 0.22056438662814234,
 0.21764287503300353,
 0.21516574145596765,
 0.20519567041703082,
 0.20464687117164018,
 0.20082135869223647,
 0.1987615979999813,
 0.19781414201873612,
 0.19781414201873612,
 0.19744962591969747,
 0.19605723255834875,
 0.191662969499982,
 0.19086611143795612,
 0.19069251784911845,
 0.1893206114156883,
 0.18650096164806276,
 0.18257418583505539,
 0.18219813149998285,
 0.18077538151554684,
 0.18077538151554684,
 0.17895849739771977,
 0.17895849739771977,
 0.17785945835997752,
 0.17395415281425125,
 0.17391639824998364,
 0.17391639824998364,
 0.1721325931647741,
 0.17213259316477408,
 0.16865480854231357,
 0.16770509831248423,
 0.167093470609201,
 0.167093470609201,
 0.1669931442893732,
 0.16666666666666666,
 0.1651445647689541,
 0.1649915822768611,
 0.16228816518671588,
 0.1606438657804998,
 0.15811388300841897,
 0.15731330124142318,
 0.15731330124142318,
 0.15569978883230462,
 0.15569978883230462,
 0.15555555555555556,
 0.15525933593055521,
 0.15220988371246985,
 0.15220988371246985,
 0.15214515486254615,
 0.1511857892036909,
 0.1502496452850696,
 0.14907119849998599,
 0.1475729574745244,
 0.14757295747452437,
 0.14704292441876157,
 0.14704292441876157,
 0.14617633655117154,
 0.14617633655117154,
 0.1455213750217998,
 0.14470719035407653,
 0.14470719035407653,
 0.14462030521243746,
 0.14322297480788657,
 0.14253932901995967,
 0.14221363894199318,
 0.14153197131580672,
 0.1414213562373095,
 0.14085904245475275,
 0.14070529413628968,
 0.1405456737852613,
 0.13968605915391566,
 0.13840913308956662,
 0.13840913308956662,
 0.13701805122009747,
 0.13608276348795434,
 0.13503191561115555,
 0.13360627800656927,
 0.13333333333333333,
 0.13333333333333333,
 0.13333333333333333,
 0.13333333333333333,
 0.13187609467915742,
 0.13176156917368248,
 0.13046561461068842,
 0.13012000972647111,
 0.13012000972647111,
 0.1297498240269205,
 0.12909944487358058,
 0.12909944487358058,
 0.12909944487358058,
 0.1285980859121099,
 0.1284457725980754,
 0.1278274981412284,
 0.12777531299998798,
 0.12777531299998798,
 0.1264911064067352,
 0.12649110640673517,
 0.12649110640673517,
 0.12598815766974242,
 0.12598815766974242,
 0.12598815766974242,
 0.12598815766974242,
 0.1252448582170299,
 0.12433397443204186,
 0.12433397443204185,
 0.12433397443204185,
 0.12433397443204185,
 0.12433397443204185,
 0.12433397443204185,
 0.12285902336679023,
 0.12253577034896798,
 0.12253577034896797,
 0.12253577034896797,
 0.12253577034896797,
 0.12253577034896797,
 0.12213224860438321,
 0.12171612389003693,
 0.12171612389003693,
 0.12130422381234185,
 0.12091270835166862,
 0.12091270835166862,
 0.12091270835166862,
 0.12091270835166862,
 0.12060453783110546,
 0.12060453783110545,
 0.12060453783110545,
 0.12060453783110545,
 0.11935247900657216,
 0.11935247900657214,
 0.11935247900657214,
 0.1192569587999888,
 0.1192569587999888,
 0.11785113019775792,
 0.11785113019775792,
 0.11744404390294068,
 0.11694106924093724,
 0.11694106924093724,
 0.1164445019479164,
 0.1164445019479164,
 0.11640504929492972,
 0.1159442654999891,
 0.11547005383792516,
 0.11501092655705904,
 0.11501092655705904,
 0.11501092655705904,
 0.1147550621098494,
 0.11359236684941297,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.1126872339638022,
 0.11268723396380219,
 0.11236664374387369,
 0.11236664374387369,
 0.1118033988749895,
 0.1118033988749895,
 0.11180339887498948,
 0.11180339887498948,
 0.11111111111111112,
 0.11111111111111112,
 0.1111111111111111,
 0.11094003924504584,
 0.1107273064716533,
 0.1107273064716533,
 0.1107273064716533,
 0.1107273064716533,
 0.10989674556596452,
 0.10989674556596452,
 0.10989674556596452,
 0.10886621079036347,
 0.10886621079036347,
 0.10872134550890704,
 0.10872134550890702,
 0.10872134550890702,
 0.1084652289093281,
 0.1084652289093281,
 0.1084652289093281,
 0.1084652289093281,
 0.10767638041163312,
 0.1070959105203332,
 0.1070959105203332,
 0.10650160840378231,
 0.10647942749999,
 0.10647942749999,
 0.10647942749999,
 0.10606601717798213,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894598,
 0.10540925533894598,
 0.10540925533894598,
 0.10540925533894598,
 0.10540925533894598,
 0.10540925533894598,
 0.10540925533894598,
 0.10540925533894598,
 0.10468478451804275,
 0.10379985922153641,
 0.10379985922153641,
 0.10379985922153641,
 0.10336227882434039,
 0.10327955589886444,
 0.10327955589886442,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10238251947232521,
 0.10238251947232521,
 0.1023825194723252,
 0.1023825194723252,
 0.1023825194723252,
 0.10226199851298272,
 0.10226199851298272,
 0.10226199851298272,
 0.10192943828752511,
 0.10143010324169743,
 0.10079052613579392,
 0.10079052613579392,
 0.10079052613579392,
 0.10079052613579392,
 0.10079052613579392,
 0.10050378152592121,
 0.10050378152592121,
 0.10050378152592121,
 0.1,
 0.1,
 0.09960238411119948,
 0.09960238411119948,
 0.09960238411119948,
 0.0994936676326182,
 0.09938079899999065,
 0.09938079899999065,
 0.09938079899999065,
 0.09938079899999065,
 0.09938079899999065,
 0.09938079899999065,
 0.09938079899999065,
 0.09938079899999065,
 0.09938079899999065,
 0.09938079899999065,
 0.09877295966495896,
 0.09877295966495896,
 0.09872481295984872,
 0.09860132971832693,
 0.09802861627917438,
 0.09802861627917438,
 0.09802861627917438,
 0.09802861627917438,
 0.0978700365857839,
 0.09773257860139563,
 0.09759000729485334,
 0.09759000729485334,
 0.09759000729485334,
 0.09759000729485333,
 0.09759000729485333,
 0.09703708495659702,
 0.097037084956597,
 0.097037084956597,
 0.0967301666813349,
 0.0967301666813349,
 0.0967301666813349,
 0.09622504486493763,
 0.09622504486493763,
 0.09622504486493763,
 0.09548198320525772,
 0.09548198320525772,
 0.09548198320525772,
 0.09548198320525772,
 0.09543305571897803,
 0.09543305571897803,
 0.09543305571897803,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09466030570784414,
 0.09428090415820634,
 0.09428090415820634,
 0.09428090415820634,
 0.09428090415820634,
 0.09428090415820634,
 0.09390602830316849,
 0.09390602830316849,
 0.09390602830316849,
 0.09390602830316849,
 0.09390602830316849,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09316949906249125,
 0.09316949906249124,
 0.09316949906249124,
 0.09312403943594377,
 0.09312403943594377,
 0.09312403943594377,
 0.09312403943594377,
 0.09245003270420486,
 0.09200874124564723,
 0.09200874124564723,
 0.09200874124564723,
 0.09200874124564723,
 0.09128709291752769,
 0.09128709291752769,
 0.09105972745135885,
 0.09105972745135885,
 0.09105972745135885,
 0.09093257859606313,
 0.09093257859606313,
 0.09093257859606313,
 0.09093257859606313,
 0.09093257859606313,
 0.09093257859606313,
 0.09093257859606313,
 0.09093257859606313,
 0.09093257859606313,
 0.09093257859606313,
 0.09093257859606313,
 0.09093257859606313,
 0.08989331499509895,
 0.08989331499509895,
 0.08989331499509895,
 0.08989331499509895,
 0.08989331499509895,
 0.08989331499509895,
 0.0894427190999916,
 0.0894427190999916,
 0.0894427190999916,
 0.0894427190999916,
 0.0894427190999916,
 0.0890870806374748,
 0.0890870806374748,
 0.08888888888888889,
 0.08888888888888889,
 0.08888888888888889,
 0.08888888888888889,
 0.08888888888888889,
 0.08888888888888889,
 0.08888888888888889,
 0.0879173964527716,
 0.0879173964527716,
 0.0879173964527716,
 0.0879173964527716,
 0.0879173964527716,
 0.0879173964527716,
 0.08784104611578833,
 0.08784104611578832,
 0.08784104611578832,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08723732043170229,
 0.08697707640712563,
 0.08697707640712563,
 0.08697707640712563,
 0.08697707640712563,
 0.08697707640712563,
 0.08697707640712563,
 0.08697707640712563,
 0.08697707640712563,
 0.08664587415167274,
 0.08606629658238706,
 0.08606629658238706,
 0.08606629658238706,
 0.08606629658238706,
 0.08606629658238706,
 0.08606629658238706,
 0.08606629658238706,
 0.08606629658238706,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238703,
 0.08549819600709618,
 0.085183541999992,
 0.085183541999992,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08439494725697222,
 0.08432740427115679,
 0.08432740427115679,
 0.08432740427115679,
 0.08432740427115679,
 0.08432740427115679,
 0.08385910090443795,
 0.08385910090443795,
 0.08385910090443795,
 0.0834965721446866,
 0.0834965721446866,
 0.08333333333333334,
 0.08304547985373997,
 0.08304547985373997,
 0.08304547985373997,
 0.08304547985373997,
 0.08304547985373997,
 0.08304547985373997,
 0.08304547985373997,
 0.08304547985373997,
 0.08304547985373997,
 0.08268982305947231,
 0.08268982305947231,
 0.08268982305947231,
 0.08268982305947231,
 0.08268982305947231,
 0.08268982305947231,
 0.08268982305947231,
 0.08268982305947231,
 0.08268982305947231,
 0.08268982305947231,
 0.08268982305947231,
 0.08190601557786016,
 0.08190601557786016,
 0.081813448945636,
 0.08164965809277261,
 0.08164965809277261,
 0.08164965809277261,
 0.08164965809277261,
 0.08164965809277261,
 0.08114408259335795,
 0.08114408259335795,
 0.08114408259335795,
 0.08114408259335795,
 0.08114408259335795,
 0.08099118235840605,
 0.08084520834544433,
 0.08040302522073697,
 0.08040302522073697,
 0.08040302522073697,
 0.08040302522073697,
 0.0803219328902499,
 0.0803219328902499,
 0.0803219328902499,
 0.0803219328902499,
 0.0803219328902499,
 0.07968190728895959,
 0.07968190728895959,
 0.07968190728895959,
 0.07968190728895959,
 0.07968190728895959,
 0.07968190728895959,
 0.07968190728895959,
 0.07968190728895959,
 0.07968190728895959,
 0.07968190728895959,
 0.07968190728895959,
 0.07936757901325452,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07897985036787898,
 0.07897985036787898,
 0.07897985036787898,
 0.07829602926862712,
 0.07829602926862712,
 0.07829602926862712,
 0.07813453848974924,
 0.07784989441615231,
 0.07784989441615231,
 0.07784989441615231,
 0.07784989441615231,
 0.07784989441615231,
 0.07784989441615231,
 0.07784989441615231,
 0.07762966796527761,
 0.07762966796527761,
 0.0769800358919501,
 0.0769800358919501,
 0.0769800358919501,
 0.0769800358919501,
 0.0769800358919501,
 0.0769800358919501,
 0.0769800358919501,
 0.0769800358919501,
 0.0769800358919501,
 0.0769800358919501,
 0.07687760066907376,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07634644457518243,
 0.07634644457518243,
 0.07607257743127308,
 0.07572824456627532,
 0.07572824456627532,
 0.07572824456627532,
 0.07567943486441664,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.0751248226425348,
 0.0751248226425348,
 0.0751248226425348,
 0.0751248226425348,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07453559924999299,
 0.07396002616336389,
 0.07396002616336389,
 0.07380124046167463,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07352146220938079,
 0.07339758434175737,
 0.07284778196108707,
 0.07284778196108707,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07254762501100118,
 0.07231015260621873,
 0.07231015260621873,
 0.07231015260621873,
 0.07231015260621873,
 0.07231015260621873,
 0.07231015260621873,
 0.07178425360775541,
 0.07178425360775541,
 0.0716114874039433,
 0.0716114874039433,
 0.0716114874039433,
 0.0716114874039433,
 0.0716114874039433,
 0.07126966450997983,
 0.07126966450997983,
 0.07126966450997983,
 0.07126966450997983,
 0.07126966450997983,
 0.07076598565790336,
 0.07076598565790336,
 0.07076598565790336,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07027283689263066,
 0.07027283689263066,
 0.07027283689263066,
 0.07027283689263066,
 0.07027283689263066,
 0.07027283689263066,
 0.07027283689263066,
 0.06984302957695783,
 0.06984302957695783,
 0.06984302957695783,
 0.06984302957695783,
 0.06984302957695783,
 0.06984302957695783,
 0.06984302957695783,
 0.06984302957695783,
 0.06978985634536183,
 0.06950480468569159,
 0.06931669932133819,
 0.06931669932133819,
 0.06931669932133819,
 0.06931669932133819,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06839855680567694,
 0.06839855680567694,
 0.06839855680567694,
 0.06839855680567694,
 0.06839855680567694,
 0.06839855680567694,
 0.06839855680567694,
 0.06839855680567694,
 0.06839855680567694,
 0.06839855680567694,
 0.06839855680567694,
 0.06839855680567694,
 0.06839855680567694,
 0.06839855680567694,
 0.06819943394704735,
 0.06819943394704735,
 0.06819943394704735,
 0.06819943394704735,
 0.06819943394704735,
 0.06819943394704735,
 0.06819943394704735,
 0.06819943394704735,
 0.06819943394704735,
 0.06819943394704735,
 0.06819943394704735,
 0.06819943394704735,
 0.06819943394704735,
 0.06795295885835008,
 0.06795295885835008,
 0.06751595780557777,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06708728072355036,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.06666666666666667,
 0.0659380473395787,
 0.0659380473395787,
 0.0659380473395787,
 0.0659380473395787,
 0.0659380473395787,
 0.0659380473395787,
 0.0659380473395787,
 0.0659380473395787,
 0.0659380473395787,
 0.0659380473395787,
 0.0654507591565088,
 0.06523280730534423,
 0.06523280730534423,
 0.06523280730534423,
 0.06523280730534423,
 0.06523280730534423,
 0.06523280730534423,
 0.06523280730534423,
 0.06523280730534423,
 0.06523280730534423,
 0.06523280730534423,
 0.06506000486323556,
 0.06506000486323556,
 0.06506000486323556,
 0.06506000486323556,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679029,
 0.06392844019805122,
 0.06388765649999399,
 0.06388765649999399,
 0.06388765649999399,
 0.06388765649999399,
 0.06388765649999399,
 0.06388765649999399,
 0.06388765649999399,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06356417261637282,
 0.06324555320336758,
 0.06324555320336758,
 0.06324555320336758,
 0.06324555320336758,
 0.06324555320336758,
 0.06324555320336758,
 0.06324555320336758,
 0.06262242910851495,
 0.06262242910851495,
 0.06262242910851495,
 0.06262242910851495,
 0.06262242910851495,
 0.06262242910851495,
 0.06262242910851495,
 0.06262242910851495,
 0.06262242910851495,
 0.06262242910851495,
 0.06262242910851495,
 0.06216698721602092,
 0.06216698721602092,
 0.06216698721602092,
 0.06216698721602092,
 0.06216698721602092,
 0.06216698721602092,
 0.06216698721602092,
 0.06216698721602092,
 0.06216698721602092,
 0.06216698721602092,
 0.06216698721602092,
 0.06216698721602092,
 0.06216698721602092,
 0.06216698721602092,
 0.062017367294604234,
 0.062017367294604234,
 0.062017367294604234,
 0.062017367294604234,
 0.062017367294604234,
 0.062017367294604234,
 0.062017367294604234,
 0.062017367294604234,
 0.062017367294604234,
 0.06183185276802244,
 0.061502080535259004,
 0.061429511683395124,
 0.061429511683395124,
 0.061429511683395124,
 0.061429511683395124,
 0.061429511683395124,
 0.061429511683395124,
 0.061429511683395124,
 0.061429511683395124,
 0.061429511683395124,
 0.061429511683395124,
 0.061429511683395124,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06030226891555273,
 0.06023386019368342,
 0.06023386019368342,
 0.059761430466719695,
 0.059761430466719695,
 0.059761430466719695,
 0.059761430466719695,
 0.059761430466719695,
 0.059761430466719695,
 0.059761430466719695,
 0.059761430466719695,
 0.059761430466719695,
 0.059761430466719695,
 0.0596284793999944,
 0.0596284793999944,
 0.0596284793999944,
 0.0596284793999944,
 0.0596284793999944,
 0.0596284793999944,
 0.0596284793999944,
 0.0596284793999944,
 0.0596284793999944,
 0.0596284793999944,
 0.0596284793999944,
 0.0596284793999944,
 0.0596284793999944,
 0.0596284793999944,
 0.0596284793999944,
 0.0596284793999944,
 0.05948588418735414,
 0.05933255459866464,
 0.05923488777590924,
 0.05923488777590924,
 0.05923488777590924,
 0.05923488777590924,
 0.05923488777590924,
 0.05923488777590923,
 0.058722021951470346,
 0.058722021951470346,
 0.058722021951470346,
 0.058722021951470346,
 0.058722021951470346,
 0.058722021951470346,
 0.058722021951470346,
 0.05847053462046862,
 0.05847053462046862,
 0.05847053462046862,
 0.05847053462046862,
 0.05847053462046862,
 0.05847053462046862,
 0.05847053462046862,
 0.05847053462046862,
 0.05847053462046862,

In [58]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]
#here enumerate say the index of movie
#herelamda x:x[1]will sort on the basis  of second column
#1:6 will print onlly first five sort no

[(1216, 0.2672612419124244),
 (2333, 0.22961557339788816),
 (582, 0.22718473369882594),
 (3730, 0.22247460415730486),
 (507, 0.22188007849009173)]

In [59]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]#it will find index of a particular movie
    distances = similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [60]:
recommend('Batman Begins')

The Dark Knight
Batman
The Dark Knight Rises
Amidst the Devil's Wings
Rockaway

In [61]:
new_df.iloc[1216]
#.dataset.iloc is used to select specific colums or row from dataset

movie_id                                                  440
title                             Aliens vs Predator: Requiem
tags        a sequel to 2004' alien vs. predator, the icon...
Name: 1216, dtype: object

In [62]:
import pickle

In [63]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [65]:
pickle.dump(similarity,open('similarity.pkl','wb'))